AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'test/**/*'
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
