services:
  app_training:
    image: ruby:3.0.2
    container_name: app_training_container
    volumes:
      - .:/app_training
    working_dir: /app_training
    command: bash -c "bundle install --redownload && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/app_training_development
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: app_training_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_training_development
      - POSTGRES_HOST_AUTH_METHOD=trust
