default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  password:

development:
  <<: *default

test:
  <<: *default
  database: app_training_test

production:
  <<: *default
  database: app_training_production
